### ISSUE TITLE
'ant' module cannot be installed using PIP

### ISSUE THREAD

**Issue by luckyLukac** [firefly-cpp/AST-Monitor#1]
Installation of 'ant' is unsuccessful. More details of the issue can be found in the attached image of the problem.

![1](https://user-images.githubusercontent.com/73126820/151007164-3d00f034-57c5-44b5-9630-4367b4832b54.jpg)

**Comment by firefly-cpp** [comment]
You are trying to install wrong package. You should install openant instead.

@luckyLukac, closing this issue now.
