### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/AST-Monitor#29]
FileNotFoundError: [Errno 2] No such file or directory: '../logs/../logs/../development/trainings/training0.json.log'

**Comment by luckyLukac** [comment]
@firefly-cpp can you please provide me with the file and the line where this error occurs?

**Comment by firefly-cpp** [comment]
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/iztok/venvs/venv1/lib64/python3.10/site-packages/ast_monitor/model.py", line 245, in <lambda>
    target=lambda: self.interval_training.start(write_log=True)
  File "/home/iztok/venvs/venv1/lib64/python3.10/site-packages/ast_monitor/interval_training.py", line 73, in start
    WriteLog.write_interval_training_header(self.log)
  File "/home/iztok/venvs/venv1/lib64/python3.10/site-packages/ast_monitor/write_log.py", line 19, in write_interval_training_header
    with open(path, 'a') as log:
FileNotFoundError: [Errno 2] No such file or directory: '../logs/../logs/../development/trainings/training0.json.log'

**Comment by luckyLukac** [comment]
@firefly-cpp can you please try it now? It worked on my system all the time, though.

**Comment by firefly-cpp** [comment]
Fixed now. Logs folder was created.

**Comment by luckyLukac** [comment]
Does this represent a global issue or it was present only on your system?

**Comment by firefly-cpp** [comment]
It is specific issue for *nix systems.

**Comment by luckyLukac** [comment]
What exactly can we do to fix this issue? As far as I am aware, the folder should be downloaded to the system when cloning the repository.

**Comment by firefly-cpp** [comment]
FIxed in [commit](https://github.com/firefly-cpp/AST-Monitor/commit/be33337cc539419fec0adc426db83f61ee578e7a).

By the way, the application is now working correctly only when running from the examples folder. We should ensure that users can run applications from anywhere.

**Comment by luckyLukac** [comment]
Agreed. Maybe that is the matter of a new issue.
