### ISSUE TITLE
Exclude `ast_monitor/map/.{gitignore,vscode}` from install

### ISSUE THREAD

**Issue by sertonix** [firefly-cpp/AST-Monitor#75]
The `ast_monitor/map/.gitignore` file and `ast_monitor/map/.vscode` directory are not excluded in the `pyproject.toml` and therefor included when installing packaging.
These files aren't needed for the functionality so could they be excluded?

**Comment by firefly-cpp** [comment]
Thanks @sertonix. You are right. We can exclude these files.

**Comment by firefly-cpp** [comment]
It is fixed now. Do you see any other problem? Otherwise, we can release a new release.

**Comment by sertonix** [comment]
> Do you see any other problem?

I don't know anything else.

**Comment by firefly-cpp** [comment]
@all-contributors please add sertonix for bug
