### ISSUE TITLE
Map problem

### ISSUE THREAD

**Issue by PajovicVanja** [firefly-cpp/AST-Monitor#91]
Translated path: C:\Users\Vanja\Desktop\pythonProject\.venv\Lib\site-packages\ast_monitor\map\dist\
127.0.0.1 - - [11/Jun/2024 14:02:55] code 404, message File not found
127.0.0.1 - - [11/Jun/2024 14:02:55] "GET / HTTP/1.1" 404 -
Translated path: C:\Users\Vanja\Desktop\pythonProject\.venv\Lib\site-packages\ast_monitor\map\dist\favicon.ico
127.0.0.1 - - [11/Jun/2024 14:02:56] code 404, message File not found
127.0.0.1 - - [11/Jun/2024 14:02:56] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by PajovicVanja** [comment]
![Screenshot 2024-06-22 112126](https://github.com/firefly-cpp/AST-Monitor/assets/74701306/71c87c25-8912-43c8-96b8-42e21ec51591)
![Screenshot 2024-06-22 112138](https://github.com/firefly-cpp/AST-Monitor/assets/74701306/e9bc3006-ab39-4e8a-b429-ba7eeead5fd0)
![Screenshot 2024-06-22 112149](https://github.com/firefly-cpp/AST-Monitor/assets/74701306/44bf15d5-7f49-4da4-96a6-e98e380dfe7b)
![Screenshot 2024-06-22 112202](https://github.com/firefly-cpp/AST-Monitor/assets/74701306/1c430e1a-5feb-4ea5-a74a-3db3f1e88b64)

**Comment by firefly-cpp** [comment]
@lahovniktadej, @alenrajsp

**Comment by lahovniktadej** [comment]
@PajovicVanja To load the map, install the dependencies in `ast_monitor/map` and start the application using the following commands:
- `cd ast_monitor/map`
- `npm install`
- `npm run dev`

The map should be available on http://localhost:5173 and within `AST-Monitor`'s GUI. Should the map not appear within `AST-Monitor`'s GUI, ensure the [map URL](https://github.com/firefly-cpp/AST-Monitor/blob/cd2396bb7633778d93fb5bacf11b5494656e69b4/ast_monitor/model.py#L97C13-L97C60) in `ast_monitor/model.py` is correctly configured and matches the URL (in this case http://localhost:5173) where the map application is running.

**Comment by lahovniktadej** [comment]
@PajovicVanja I have not been involved in the development of `AST-Monitor` apart from some minor tweaks, but from what I gather the map application does not handle the GPS simulation independently. `AST-Monitor` GUI refreshes the data using the [`update_map_component` function](https://github.com/firefly-cpp/AST-Monitor/blob/cd2396bb7633778d93fb5bacf11b5494656e69b4/ast_monitor/model.py#L124), which updates the integrated map. To refresh the data within the map application, I assume you would have to implement an infinite loop with a timeout matching the frequency of the simulation (most likely in [`ast_monitor/map/src/App.vue`](https://github.com/firefly-cpp/AST-Monitor/blob/cd2396bb7633778d93fb5bacf11b5494656e69b4/ast_monitor/map/src/App.vue), but I might be mistaken as I do not have any experience with Vue), which parses the latest GPS coordinates from the `.txt` file (created by the simulation) and calls the [`setValues` function](https://github.com/firefly-cpp/AST-Monitor/blob/cd2396bb7633778d93fb5bacf11b5494656e69b4/ast_monitor/map/src/App.vue#L22) with appropriate parameters.
